import { Language } from "@/lib";

type Coming = "coming" | "not-coming" | "maybe" | "unknown";
export type Birthday = {
  id: string;
  name: string;
  lang: Language;
  coming: Coming;
  extra?: number;
  invited?: boolean;
  comment?: string;
};

const birthdays: Birthday[] = [
  {
    id: `tap-dancing-octopus`,
    name: "Jan Paul",
    lang: "nl",
    coming: "coming",
    invited: true,
  },
  {
    id: "trampoline-jumping-cactus",
    name: "Stephanie",
    lang: "nl",
    coming: "coming",
    invited: true,
  },
  {
    id: "marshmallow-weightlifting-champ",
    name: "Vera",
    lang: "nl",
    coming: "unknown",
    invited: true,
  },
  {
    id: "hula-hooping-cactus",
    name: "Martin",
    lang: "nl",
    coming: "unknown",
    invited: true,
  },
  {
    id: "skydiving-sheep-baaas",
    name: "Nina",
    lang: "nl",
    coming: "unknown",
    invited: true,
  },
  {
    id: "tightrope-walking-elephant",
    name: "Mick",
    lang: "nl",
    coming: "unknown",
    invited: true,
  },
  {
    id: "sunbathing-owl-tans",
    name: "Nevil & Ans",
    lang: "nl",
    coming: "unknown",
    extra: 1,
  },
  {
    id: "burping-flower-blooms",
    name: "Fabienne",
    lang: "nl",
    coming: "unknown",
    invited: true,
  },
  {
    id: "invisible-dog-barks",
    name: "Patricia & Rens",
    lang: "nl",
    coming: "unknown",
    extra: 1,
  },
  {
    id: "jumping-cake-escapes",
    name: "Danielle",
    lang: "nl",
    coming: "unknown",
    invited: true,
  },
  {
    id: "roller-skating-baguette",
    name: "Roos & Wilfred",
    lang: "nl",
    coming: "unknown",
    extra: 1,
  },
  {
    id: "sleepwalking-pillow-fights",
    name: "Liam",
    lang: "nl",
    coming: "unknown",
    comment: "van Anna",
    invited: true,
  },
  {
    id: "marching-mole-marvels",
    name: "Anna",
    lang: "nl",
    coming: "unknown",
    comment: "van Liam",
    invited: true,
  },
  {
    id: "moon-cheese-melts",
    name: "Floor & Ralph",
    lang: "nl",
    coming: "unknown",
    extra: 1,
  },
  {
    id: "cartwheeling-walrus-flops",
    name: "Charita",
    lang: "nl",
    coming: "unknown",
    invited: true,
  },
  { id: "surfing-cow-moos", name: "Sidney", lang: "nl", coming: "unknown" },
  {
    id: "whistling-teapot-dances",
    name: "Anouk",
    lang: "nl",
    coming: "unknown",
    comment: "van Ivo",
    invited: true,
  },
  {
    id: "giggly-goat-gallops",
    name: "Ivo",
    lang: "nl",
    coming: "unknown",
    comment: "van Anouk",
    invited: true,
  },
  {
    id: "yodeling-pickle-echoes",
    name: "Maartje & Jasper",
    lang: "nl",
    coming: "unknown",
    extra: 1,
  },
  {
    id: "photobombing-ghost-appears",
    name: "Jip",
    lang: "nl",
    coming: "unknown",
  },
  {
    id: "blushing-lobster-crawls",
    name: "Siem",
    lang: "nl",
    coming: "unknown",
  },
  { id: "giggling-toast-jump", name: "Tim", lang: "nl", coming: "unknown" },
  {
    id: "spy-penguin-disguises",
    name: "Nathalie",
    lang: "se",
    coming: "unknown",
    extra: 1,
  },
  {
    id: "bungee-jumping-turtle",
    name: "Melanie",
    lang: "se",
    coming: "unknown",
  },
  {
    id: "moonwalking-shoe-unties",
    name: "Martijn",
    lang: "nl",
    coming: "unknown",
    comment: `Martijn Groenewegen, DHL`,
  },
  {
    id: "gossiping-plants-whisper",
    name: "Martijn",
    lang: "nl",
    coming: "unknown",
    comment: `Martijn Clarenbeek, DHL`,
  },
  {
    id: "mystery-potato-vanishes",
    name: "Daniel",
    lang: "nl",
    coming: "unknown",
    comment: `DHL`,
  },
  {
    id: "disco-yeti-grooves",
    name: "Jesse",
    lang: "nl",
    coming: "unknown",
    comment: `DHL`,
  },
  {
    id: "karate-kitten-chops",
    name: "Serge",
    lang: "nl",
    coming: "unknown",
    comment: `DHL`,
  },
  {
    id: "cheeky-moon-winks",
    name: "Anna",
    lang: "nl",
    coming: "unknown",
    comment: `DHL`,
  },
  {
    id: "ticklish-sun-laughs",
    name: "Andre",
    lang: "nl",
    coming: "unknown",
    comment: `DHL`,
  },
  {
    id: "alien-socks-dance",
    name: "Merlijn",
    lang: "nl",
    coming: "unknown",
    comment: `DHL`,
  },
  {
    id: "singing-fish-giggles",
    name: "Thomas",
    lang: "nl",
    coming: "unknown",
    comment: `DHL`,
  },
  {
    id: "sassy-cloud-squirts",
    name: "Stef",
    lang: "nl",
    coming: "unknown",
    comment: `DHL`,
  },
  {
    id: "flying-pig-winks",
    name: "Linda",
    lang: "nl",
    coming: "unknown",
    comment: `voetbal`,
  }, // voetbal
  {
    id: "sneezing-cupcake-frosting",
    name: "Alessandra",
    lang: "nl",
    coming: "unknown",
    comment: `voetbal`,
  },
  {
    id: "breakdancing-banana-slips",
    name: "Rens & Imane",
    lang: "nl",
    coming: "unknown",
    extra: 1,
  },
  {
    id: "dancing-robot-malfunctions",
    name: "Lita",
    lang: "nl",
    coming: "unknown",
  },
  {
    id: "couch-potato-sprouts",
    name: "Mike",
    lang: "nl",
    coming: "unknown",
  },
  {
    id: "lazy-sofa-naps",
    name: "Remco & Sim",
    lang: "nl",
    coming: "unknown",
    extra: 1,
  },
  {
    id: "ninja-cat-bathes",
    name: "Bas & Monique",
    lang: "nl",
    coming: "unknown",
    extra: 1,
  },
  { id: "hungry-book-eats", name: "Katja", lang: "nl", coming: "unknown" },
  {
    id: "time-traveling-snail",
    name: "Jordy",
    lang: "nl",
    coming: "unknown",
  },
  { id: "wizard-hat-flies", name: "Fabio", lang: "nl", coming: "unknown" },
  {
    id: "pirate-duck-quacks",
    name: "Pietro & Raffaella",
    lang: "nl",
    coming: "unknown",
    extra: 1,
  },
  {
    id: "flirty-mirror-winks",
    name: "Marjolein",
    lang: "nl",
    coming: "unknown",
  },
  {
    id: "giant-snail-races",
    name: "Marc & Christien",
    lang: "nl",
    coming: "unknown",
    extra: 1,
  },
  {
    id: "sneaky-fridge-raids",
    name: "Emre & Meryem",
    lang: "en",
    coming: "unknown",
    extra: 1,
  },
  {
    id: "napping-dragon-drools",
    name: "Patricia",
    lang: "en",
    coming: "unknown",
    comment: "Sawamura",
  },
  {
    id: "exploding-pizza-sauce",
    name: "Cindy & Anita",
    lang: "nl",
    coming: "unknown",
    extra: 1,
  },
  {
    id: "bubbly-bear-burps",
    name: "Eva Luna",
    lang: "nl",
    coming: "unknown",
    invited: true,
  },
  {
    id: "quirky-quokka-queries",
    name: "Anne Lieve",
    lang: "nl",
    coming: "unknown",
    invited: true,
  },
  {
    id: "ninja-narwhal-navigates",
    name: "Alexander",
    lang: "nl",
    coming: "unknown",
    invited: true,
  },
  {
    id: "fluffy-fox-frolics",
    name: "Mignon",
    lang: "nl",
    coming: "unknown",
  },
];

[
  "glittery-goose-gambles",
  "prancing-penguin-panics",
  "cackling-crow-codes",
  "wobbly-wombat-wanders",
  "zany-zebra-zooms",
  "quirky-quail-quizzes",
  "gargling-giraffe-giggles",
  "bouncing-badger-boxes",
  "dizzy-dragon-doodles",
  "elegant-eagle-eats",
  "fancy-frog-fashions",
  "hopping-hedgehog-hiccups",
  "itchy-iguana-iceskates",
  "jazzy-jellyfish-jumps",
  "kickboxing-kangaroo-knits",
  "leaping-llama-laughs",
  "munching-monkey-moonwalks",
  "nifty-newt-naps",
  "oily-octopus-organizes",
  "puzzled-panda-paints",
  "quirky-quetzal-questions",
  "rapping-raccoon-rafts",
  "silly-squid-squirts",
  "twerking-turtle-travels",
  "unicycling-unicorn-updates",
  "voguing-vulture-vacations",
  "wacky-walrus-washes",
  "xenial-xerus-x-rays",
  "yawning-yak-yodels",
  "zealous-zucchini-zips",
  "acrobat-ant-accelerates",
  "baking-bat-balloons",
  "cartwheeling-cat-calls",
  "diving-dolphin-doodles",
  "energetic-emu-emails",
  "flying-ferret-fiddles",
  "galloping-gorilla-gargles",
  "hovering-hamster-hums",
  "impish-impala-implies",
  "jumping-jaguar-jokes",
  "karaoke-koala-kayaks",
  "lounging-lemur-lectures",
  "napping-newt-notices",
  "orbiting-ostrich-objects",
];

export const useBirthday = (id: string): Birthday | undefined =>
  birthdays.find((b) => b.id === id);

export const useAllBirthdays = (): Birthday[] => Object.values(birthdays);
