name: Build elidon-website
run-name: ${{ github.actor }} builds the website 🚀
on: [push]
jobs:
  Build-The-Website:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event @ ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Install packages
        run: |
          yarn install
      - name: Build the website
        run: |
          yarn build
      - name: Run eslint
        run: |
          yarn lint
      - run: echo "🍏 This job's status is ${{ job.status }}."